# Generated by Django 3.1.5 on 2021-01-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('constante_para_calculo_de_frete', models.DecimalField(decimal_places=1, max_digits=2)),
                ('altura_minima', models.PositiveSmallIntegerField()),
                ('altura_maxima', models.PositiveSmallIntegerField()),
                ('largura_minima', models.PositiveSmallIntegerField()),
                ('largura_maxima', models.PositiveSmallIntegerField()),
                ('prazo_entrega', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Transportadora',
                'verbose_name_plural': 'Transportadoras',
            },
        ),
    ]
